version: '2.1'
services:
  postgres:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=cp_user
      - POSTGRES_PASSWORD=albert1904
      - POSTGRES_DB=cp_project
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
  app:
    image: carsandp
    restart: always
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
    - postgres