# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0003_auto_20190418_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
