# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 08:17
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cp_app', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=160)),
                ('cars', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modified_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('deleted_at', unixtimestampfield.fields.UnixTimeStampField(default=0)),
            ],
        ),
    ]
