# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 08:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0005_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='cars',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
