# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 09:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp_app', '0006_auto_20190420_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
