# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cp_app', '0008_auto_20190420_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
    ]
