# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 12:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cp_app', '0015_auto_20190420_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('average_fuel', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('delegation_starting', unixtimestampfield.fields.UnixTimeStampField(default=0)),
                ('delegation_ending', unixtimestampfield.fields.UnixTimeStampField(default=0)),
                ('driver', models.CharField(max_length=160)),
                ('owner', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('pr', 'private'), ('co', 'company')], default='co', max_length=2)),
                ('partners', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('created_at', unixtimestampfield.fields.UnixTimeStampField(auto_now_add=True)),
                ('modify_at', unixtimestampfield.fields.UnixTimeStampField(auto_now=True)),
                ('deleted_at', unixtimestampfield.fields.UnixTimeStampField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
